config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root 'home#index'
  get 'search',   to: 'home#search'
  get 'design',   to: 'categories#design'
  get 'music',    to: 'categories#music'
  get 'movie',    to: 'categories#movie'
  get 'it',       to: 'categories#it'
  get 'business', to: 'categories#business'
  get 'language', to: 'categories#language'
  get 'beauty',   to: 'categories#beauty'
  get 'hobby',    to: 'categories#hobby'
  get 'other',    to: 'categories#other'
  get 'level1',    to: 'categories#level1'
  get 'level2',    to: 'categories#level2'
  get 'level3',    to: 'categories#level3'
  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    get     'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch   'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships,  class_name: "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: "visitor_id",
                                  dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: "visited_id",
                                   dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :user_name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :gender,  length: { maximum: 5 }
  validates :comment, length: { maximum: 120 }

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user ||= User.create(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        user_name: auth.info.name,
        password: Devise.friendly_token[0, 20],
        image: auth.info.image
      )
    end
    user
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search)
    if search
      where(['user_name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where([
      "visitor_id = ? and visited_id = ? and action = ? ",
      current_user.id, id, 'follow',
    ])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def profile_edit
  end

  def profile_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
      redirect_to current_user, notice: 'プロフィールを更新しました'
    else
      render "profile_edit"
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    # flash[:success] = "Welcome to the Working!"
    current_user
  end

  def after_sign_in_path_for(resource)
    # flash[:success] = "Welcome to the Working!"
    current_user
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [
    :index, :destroy,
    :following, :followers,
  ]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary us-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-info us-btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <% if user.image %>
     <%= image_tag user.image, :width =>'50px',:height =>'50px' %>
   <% else %>
     <%= gravatar_for user , size: 50 %>
   <% end %>
  <%= link_to user.user_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %><br>
  <%= user.comment %>
</li>

app/views/users/index.html.erb
<% provide(:title, "Search") %>
<div class="col-xs-12 col-md-3 ui">
  <h1>インストラクターを探す</h1>
  <%= form_tag(users_path, :method => 'get') do %>
    <%= text_field_tag :search, "ex) Example User", {class: "search-form"} %>
    <%= submit_tag 'Search', :user_name => nil, class: "btn btn-primary search-btn" %>
  <% end %>
</div>
<div class="col-xs-12 col-md-9">
  <ul class="users">
    <%= render @users %>
  </ul>
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="row">
  <div class="profile-top">
    <aside class="col-xs-4">
      <section class="user_info">
        <h1>
         <% if @user.image %>
           <%= image_tag @user.image, :width =>'80px',:height =>'80px' %>
         <% else %>
           <%= gravatar_for @user , size: 80 %>
         <% end %>
         <%= @user.user_name %>
        </h1>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
        <%= render 'follow_form' if user_signed_in? %>
      </section>
      <% if current_user?(@user) %>
        <div class="us-user">
          <p>
            <%= link_to 'プロフィール編集', profile_edit_path %>
            <span class="glyphicon glyphicon-edit icon" aria-hidden="true"></span>
          </p>
          <p>
            <%= link_to "新しいLessonを開講する", new_micropost_path %>
            <span class="glyphicon glyphicon-edit icon" aria-hidden="true"></span>
          </p>
          <p>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </p>
        </div>
      <% end %>
    </aside>
    <div class="col-xs-8 profile-right">
        <p>氏名 : <%= @user.name %></p>
        <p>性別 : <%= @user.gender %></p>
        <p>自己紹介 : <%= @user.comment %></p>
      </div>
    </div>
  </div>
  <div class="col-12 us">
    <% if @user.microposts.any? %>
      <h3>Lessons</h3>
      <ol class="us-microposts">
        <% @microposts.each do |micropost| %>
          <div class="col-xs-4 col-md-2">
            <%= render 'microposts/pictures',  micropost: micropost %>
          </div>
        <% end %>
      </ol>
    <% end %>
    <%= will_paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.user_name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>