config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root 'home#index'
  get 'search',   to: 'home#search'
  get 'design',   to: 'categories#design'
  get 'music',    to: 'categories#music'
  get 'movie',    to: 'categories#movie'
  get 'it',       to: 'categories#it'
  get 'business', to: 'categories#business'
  get 'language', to: 'categories#language'
  get 'beauty',   to: 'categories#beauty'
  get 'hobby',    to: 'categories#hobby'
  get 'other',    to: 'categories#other'
  get 'level1',    to: 'categories#level1'
  get 'level2',    to: 'categories#level2'
  get 'level3',    to: 'categories#level3'
  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    get     'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch   'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/shared/_category_index.html.erb
<div class="hi-categories_index">
  <h1>カテゴリ一覧</h1>
  <div class="hi-index">
    <p class="hi-cate"><%= link_to 'デザイン', design_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to '音楽', music_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to '動画、写真、画像', movie_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to 'IT、プログラミング', it_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to 'ビジネス', business_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to '語学', language_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to '美容', beauty_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to '趣味、エンタメ', hobby_path, class: "hi-cate_link" %></p>
    <p class="hi-cate"><%= link_to 'その他', other_path, class: "hi-cate_link" %></p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ul class="hi-microposts hi-resl">
    <% @feed_items.each do |micropost| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'microposts/micropost',  micropost: micropost %>
      </div>
    <% end %>
  </ul>
  <ul class="hi-microposts hi-ress">
    <% @feed_items.limit(6).each do |micropost| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'microposts/micropost',  micropost: micropost %>
      </div>
    <% end %>
  </ul>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<p><%= current_user.user_name %></p>