config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root 'home#index'
  get 'search',   to: 'home#search'
  get 'design',   to: 'categories#design'
  get 'music',    to: 'categories#music'
  get 'movie',    to: 'categories#movie'
  get 'it',       to: 'categories#it'
  get 'business', to: 'categories#business'
  get 'language', to: 'categories#language'
  get 'beauty',   to: 'categories#beauty'
  get 'hobby',    to: 'categories#hobby'
  get 'other',    to: 'categories#other'
  get 'level1',    to: 'categories#level1'
  get 'level2',    to: 'categories#level2'
  get 'level3',    to: 'categories#level3'
  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    get     'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch   'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recently_post = Micropost.take(3)
    @level1 = Micropost.where(level: "初級者").limit(4)
    @level2 = Micropost.where(level: "中級者").limit(4)
    @level3 = Micropost.where(level: "上級者").limit(4)
    @designs = Micropost.where(category: "デザイン").limit(4)
    @musics = Micropost.where(category: "音楽").limit(4)
    @movies = Micropost.where(category: "動画、写真、画像").limit(4)
    @its = Micropost.where(category: "IT、プログラミング").limit(4)
    @businesses = Micropost.where(category: "ビジネス").limit(4)
    @languages = Micropost.where(category: "語学").limit(4)
    @beauties = Micropost.where(category: "美容").limit(4)
    @hobbies = Micropost.where(category: "趣味、エンタメ").limit(4)
    @others = Micropost.where(category: "その他").limit(4)
    if user_signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 8)
    end
  end

  def search
    @microposts = Micropost.search_micropost(params[:search])
  end
end

app/views/home/_category.html.erb
<div class="hi-designs col-xs-12">
  <%= link_to(design_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-pencil icon" aria-hidden="true"></span>
      デザイン
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @designs.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @designs.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(music_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-music icon" aria-hidden="true"></span>
      音楽
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @musics.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @musics.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(movie_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-facetime-video icon" aria-hidden="true"></span>
      動画、写真、画像
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @movies.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @movies.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(it_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-apple icon" aria-hidden="true"></span>
      IT、プログラミング
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @its.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @its.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(business_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-usd icon" aria-hidden="true"></span>
      ビジネス
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @businesses.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @businesses.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(language_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-education icon" aria-hidden="true"></span>
      語学
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @languages.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @languages.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(beauty_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-heart icon" aria-hidden="true"></span>
      美容
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @beauties.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @beauties.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(hobby_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-sunglasses icon" aria-hidden="true"></span>
      趣味、エンタメ
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @hobbies.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @hobbies.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(other_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-option-horizontal icon" aria-hidden="true"></span>
      その他
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @others.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @others.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>

app/views/home/_level.html.erb
<div class="hi-designs col-xs-12">
  <%= link_to(level1_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-pawn icon" aria-hidden="true"></span>
      初級者
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @level1.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @level1.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(level2_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-knight icon" aria-hidden="true"></span>
      中級者
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @level2.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @level2.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<div class="hi-designs col-xs-12">
  <%= link_to(level3_path, class: 'hi-link') do %>
    <h4>
      <span class="glyphicon glyphicon-king icon" aria-hidden="true"></span>
      上級者
    </h4>
  <% end %>
  <ol class="hi-microposts hi-resl">
    <% @level3.each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
  <ol class="hi-microposts hi-ress">
    <% @level3.limit(3).each do |category| %>
      <div class="col-xs-4 col-md-3">
        <%= render 'categories/category', category: category%>
      </div>
    <% end %>
  </ol>
</div>
<p class="empty">a</p>

app/views/home/index.html.erb
<div class="row">
  <div class="col-xs-12 hi-top">
    <h3>最新のレッスン</h3>
    <div class="hi-recently_microposts">
      <% @recently_post.each do |category| %>
        <div class="col-xs-4">
          <%= render 'categories/category', category: category%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-3  category-list">
    <%= render 'shared/category_index' %>
    <% if user_signed_in? %>
      <section class="user_info parsonal">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    <% end %>
  </div>
  <div class="col-md-9">
    <div class="hi-lessons">
      <% if user_signed_in? %>
        <div class="hi-recommend">
          <p class="empty">a</p>
          <h3>オススメのレッスン</h3>
          <%= render 'shared/feed' %>
        </div>
      <% end %>
      <div class="col-xs-12 hi-categories">
        <h3>レベル別</h3>
        <%= render 'home/level' %>
      </div>
      <div class="col-xs-12 hi-categories">
        <h3 class="hi-title_cate">カテゴリ別</h3>
        <%= render 'home/category' %>
      </div>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<% provide(:title, "Search") %>
<div class="col-xs-12 col-md-3 ui">
  <h1>レッスンを探す</h1>
  <%= form_tag(search_path,:method => 'get') do %>
    <%= text_field_tag :search, "ex) プログラミング、ピアノ", {class: "search-form"} %>
    <%= submit_tag 'Search', :name => nil, class: "btn btn-primary search-btn"  %>
  <% end %>
</div>
<div class="col-xs-12 col-md-9">
  <div class="hi-lessons">
    <div class="hi-categories">
      <ol class="hi-microposts">
        <% @microposts.each do |category| %>
          <div class="col-xs-4 col-md-3">
            <%= render 'categories/category', category: category%>
          </div>
        <% end %>
      </ol>
    </div>
  </div>
</div>