config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  root 'home#index'
  get 'search',   to: 'home#search'
  get 'design',   to: 'categories#design'
  get 'music',    to: 'categories#music'
  get 'movie',    to: 'categories#movie'
  get 'it',       to: 'categories#it'
  get 'business', to: 'categories#business'
  get 'language', to: 'categories#language'
  get 'beauty',   to: 'categories#beauty'
  get 'hobby',    to: 'categories#hobby'
  get 'other',    to: 'categories#other'
  get 'level1',    to: 'categories#level1'
  get 'level2',    to: 'categories#level2'
  get 'level3',    to: 'categories#level3'
  devise_scope :user do
    get     '/signup',         to: 'users/registrations#new'
    post    '/signup',         to: 'users/registrations#create'
    get     '/users/edit',     to: 'users/registrations#edit'
    patch   '/users/:id',      to: 'users/registrations#update'
    get     'login',           to: 'users/sessions#new'
    post    '/login',          to: 'users/sessions#create'
    delete  '/logout',         to: 'users/sessions#destroy'
    get     '/password/reset/new', to: 'users/passwords#new'
    post    'user/password',       to: 'users/passwords#create'
    get     'users/password/edit', to: 'users/passwords#edit'
    patch   'users/password', to: 'users/passwords#update'
    get     'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch   'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:new, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class=" navbar-fixed-top ">
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "soonikl", root_path, id:"logo" %>
      </div>
      <nav>
        <ul id="navbar" class="nav navbar-nav navbar-right ">
          <% if user_signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <% if unchecked_notifications.any? %>
              <li class="notification blinking">
                <%= link_to "通知", notifications_path %>
              </li>
            <% else %>
              <li><%= link_to "通知", notifications_path %></li>
            <% end %>
            <li><%= link_to 'マイページ', current_user %></li>
          <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', login_url %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
  <div class="navbar navbar-inverse navbar1">
    <div class="container">
      <div class="topBar">
        <div class="container">
          <div class="row">
            <div class="col-xs-7 ">
              <ul class="list-inline navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-list"><%= link_to 'インストラクターを探す', users_path %></li>
                  <li class="nav-list"><%= link_to '|'%></li>
                  <li class="nav-list"><%= link_to 'レッスンを探す', search_path %></li>
                <% else %>
                  <li class="nav-list"><%= link_to 'インストラクターを探す', users_path %></li>
                  <li class="nav-list"><%= link_to '|'%></li>
                  <li class="nav-list"><%= link_to 'レッスンを探す', search_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="col-xs-5">
              <ul class="list-inline pull-right navbar-nav">
                <% if user_signed_in? %>
                  <li class="nav-list"><%= link_to '新しいレッスンを開講', new_micropost_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCk7uZWLKBFFPNiMOvqwlTWA_ciD_rlqwo&callback=initMap" async defer></script>
    </div>
  </body>
</html>